apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cluster-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops-cluster-config
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-config/cluster-resources
    repoURL: https://github.com/chrismulderza/openshift-gitops-ops-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
