# OpenShift GitOps Operator deployment defaults
argocd:
  operator:
    subscription:
      name: openshift-gitops-operator
      namespace: openshift-operators
      channel: latest
      source: redhat-operators
  deployment:
    project:
      name: openshift-gitops
    instance:
      name: openshift-gitops
      namespace: openshift-gitops
      adminUser: admin
  clusterRole:
    name: openshift-gitops-manage-cluster-role
  roleBinding:
    name: openshift-gitops-manage-cluster
    roleRef:
      name: openshift-gitops-manage-cluster-role
    subjects:
      name: openshift-gitops-argocd-application-controller
      namespace: openshift-gitops
